blog_app/accounts/urls.py
from django.conf.urls import url
from django.urls import path, include
from .import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),
]

blog_app/articles/urls.py
from django.urls import path
from .import views

app_name = 'articles'
urlpatterns = [
    path('',views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/',views.article_detail, name="detail")
]

blog_app/blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('about/',views.about),
    path('articles/',include('articles.urls')),
    path('',article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/accounts/models.py
from django.db import models

# Create your models here.

blog_app/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

blog_app/articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

blog_app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

blog_app/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, "articles/article_list.html", {'articles':articles})

def article_detail(request,slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html',{'form':form})

blog_app/blog_app/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, "home.html")
def about(request):
    return render(request, "about.html")

blog_app/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block body %}
    <h1>Log In</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

blog_app/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block body %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

blog_app/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block body %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create">
        </form>
    </div>
    
{% endblock %}

blog_app/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block body %}
    <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}">
            <h2>{{article.title}}</h2>
            <p>{{article.body}}</p>
            <p>{{article.date}}</p>
            <p>Author: {{article.author}}</p>
        </div>
    </div>
{% endblock %}

blog_app/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block body%}
        <h1>All Articles Over Here!!!!</h1>
        <p>Welcome to Our Blog Website</p>
        <div class="articles">
            {% for article in articles %}
                <div class="article">
                    <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                    <p>{{article.snippet}}</p>
                    <p>{{article.date}}</p>
                    <p>Author: {{article.author}}</p>
                </div>
            {% endfor%}
        </div>
{% endblock%}

blog_app/templates/about.html
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title> 
    </head>
    <body>
        <h1>This is About Page</h1>
        <p>Welcome to Our Blog Website</p>
    </body>
</html>

blog_app/templates/base_layout.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <title>Article List</title> 
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="area">
                    <div class="wrapper circles">
                    <h1><a href="{% url 'home' %}"><img style="width: 200px;" src="{% static 'blogLogo.png'%}"></a></h1>
                    <nav class="context">
                        <ul>
                            {% if user.is_authenticated %}
                                <li>
                                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                                        {% csrf_token%}
                                        <button type="submit">LogOut</button>
                                    </form>
                                </li>
                                <li><a href="{% url 'articles:create' %}" class="highlight">Create Article</a></li>
                            
                            {% else %}
                                <li><a href="{% url 'accounts:login'%}">Login</a></li>
                                <li><a href="{% url 'accounts:signup'%}">SignUp</a></li>
                            {% endif %}
                            
                        </ul>
                    </nav>
                    {% block body %}
                    {% endblock%}
                </div>
        </div>
        
    </body>
    
    <script src="{% static 'slugify.js' %}"></script>
</html>

blog_app/templates/home.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Home</title> 
    </head>
    <body>
        <h1>This is Home Page</h1>
        <p>Welcome to Our Blog Website</p>
    </body>
</html>